# Generated by Django 4.2 on 2023-10-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_image_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="count",),
        migrations.RemoveField(model_name="product", name="is_active",),
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(default="Hyundai", max_length=255),
        ),
    ]
