# Generated by Django 4.2 on 2023-10-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_product_count_remove_product_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpareParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("description", models.TextField(null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="spare_parts_images/"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_parts",
                        to="api.category",
                    ),
                ),
            ],
        ),
    ]
