networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend  
    networks:
      - dev
  backend:
    container_name: backend
    build:
      context: ./backend/back
    networks:
      - dev
  frontend:
    build:
      context: ./auto-access2
    networks:
      - dev
